# Generated by Django 3.1.5 on 2021-03-19 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 12, 58, 39, 507890)),
        ),
    ]
