# Generated by Django 3.1.5 on 2021-03-22 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210319_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 13, 49, 43, 540664)),
        ),
    ]
