# Generated by Django 3.1.5 on 2021-03-31 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20210322_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='like',
            field=models.ManyToManyField(blank='True', to='network.Profile'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 13, 18, 38, 59101)),
        ),
    ]
