# Generated by Django 3.1.5 on 2021-04-06 11:12

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20210406_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 14, 12, 56, 45088)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='like',
            field=models.ManyToManyField(blank='True', related_name='Likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
